
-- Run this in your Supabase Dashboard -> SQL Editor

-- 1. Add judge_code to tournaments
alter table tournaments add column if not exists judge_code text;

-- 2. Create tournament_judges table
create table if not exists tournament_judges (
  id bigint generated by default as identity primary key,
  tournament_id uuid references tournaments(id) on delete cascade not null,
  user_id text not null, -- Stack Auth User ID
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(tournament_id, user_id)
);

-- 3. RLS Policies (Optional but good practice if RLS is enabled)
alter table tournament_judges enable row level security;

-- Allow read access to everyone (so we can check if someone is a judge)
create policy "Public can view judges" on tournament_judges for select using (true);
